on:
- push
- pull_request

name: Coveralls

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v1

    - name: Setup ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6

    - name: Build and test with rake
      run: |
        gem install bundler
        bundle install
        bundle exec rake spec

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
